const allRoles = {
  user: [],
  customer: [
    'viewOwnCompany',
    'manageOwnCompany',
    'viewOwnBookings',
    'manageOwnBookings',
    'viewOwnInvoices',
    'viewOwnContracts',
    'manageOwnContracts',
    'viewOwnDocuments',
    'manageOwnDocuments',
    'viewOwnPayments',
    'manageOwnPayments',
    'viewPromotions',
    'viewOwnNotifications',
    'viewOwnEcommerce',
    'manageOwnEcommerce',
  ],
  driver: [],
  operator: [
    'getUsers',
    'manageUsers',
    'manageWarehouse',
    'manageLeads',
    'manageGeofences',
    'managePricing',
    'viewPromotions',
    'managePromotions',
    'viewAllBookings',
    'viewAllCompanies',
    'viewAllInvoices',
    'viewAllNotifications',
    'viewOpsDashboard',
    'viewAllDrivers',
    'viewAllTrips',
  ],
  admin: [
    'getUsers',
    'manageUsers',
    'manageWarehouse',
    'manageLeads',
    'manageGeofences',
    'managePricing',
    'viewPromotions',
    'managePromotions',
    'viewOwnEcommerce',
    'manageOwnEcommerce',
    'viewAllBookings',
    'viewAllCompanies',
    'viewAllInvoices',
    'viewAllNotifications',
    'viewOpsDashboard',
    'viewAllDrivers',
    'viewAllTrips',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
